
# 3.8 python image 
FROM python:3.8 

# Set the working directory to /app
WORKDIR /app

# Copy requierements
COPY requirements.txt requirements-test.txt requirements-dev.txt ./

# update pip
RUN pip install --upgrade pip

# Install requierements
RUN pip install -r requirements.txt
RUN pip install -r requirements-test.txt
RUN pip install -r requirements-dev.txt


#CMD ["sh", "-c", "while true; do sleep 86400; done"]
ENTRYPOINT ["make"]
