name: Build and Push to Docker Hub with SemVer

on:
  push:
    # When tags of the form v0.1.1-something are pushed, trigger this workflow
    tags:
      - 'v*.*.*-*'
      - 'v*.*.*'

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up Docker Buildx
    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    # Log in to Docker Hub, set secrets in Settings > Secrets
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Build and push to Docker Hub with SemVer tag
    - name: Build and push to Docker Hub
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile.prod
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/latam-mle-challenge:${{ github.ref_name }}
