

name: CI Pipeline

on:
  pull_request:
    branches: 
      - main
      - develop

jobs:
  build_and_run:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Step to create a symbolic link
    - name: Create symbolic link
      run: ln -s docker-compose.test.yml docker-compose.override.yml

    # Build using Docker Compose
    - name: Build and start containers with Docker Compose
      run: |
        docker-compose build

    # Execute the model-test command
    - name: Execute model-test command
      run: docker-compose run -T flight-prophet model-test
      # '-T' disables pseudo-tty allocation

    # Execute the api-test command
    - name: Execute api-test command
      run: docker-compose run -T flight-prophet api-test
